# Generated by Django 5.2.9 on 2025-12-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('rider_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mob_number', models.IntegerField(blank=True, max_length=15)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_fc', models.DateField(blank=True, null=True)),
                ('rider_photo', models.ImageField(blank=True, null=True, upload_to='rider_photos/')),
                ('vehicle_photo', models.ImageField(blank=True, null=True, upload_to='vehicle_photos/')),
                ('license_photo', models.ImageField(blank=True, null=True, upload_to='license_photos/')),
                ('rating', models.FloatField(default=5.0)),
                ('total_trips', models.IntegerField(default=0)),
                ('complaints', models.IntegerField(default=0)),
            ],
        ),
    ]
