# Generated by Django 5.2.9 on 2025-12-03 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='trip_user', serialize=False, to='rider.riderprofile')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('mob_number', models.IntegerField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('trip_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='trip_detail',
            fields=[
                ('trip_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='trip_driver', serialize=False, to='user.userprofile')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('distance_km', models.FloatField()),
                ('fare', models.FloatField()),
                ('trip_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('rider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider.riderprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('complaint_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('complaint_text', models.TextField()),
                ('complaint_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.trip_detail')),
            ],
        ),
    ]
